name: MLOps Workflow

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest
    environment: mlops_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Config aws credentials
      run: |
        dvc remote add -d myremote ${{ secrets.AWS_S3_BUCKET_URL }} --force
        dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Repro data
      run: |
        dvc repro
        
    - name: Pull data from DVC storage
      run: |
        dvc pull

    - name: Train model
      run: |
        python3 src/train.py --data_path data/chest_xray --epochs ${model.epochs} --batch_size ${model.batch_size}

    - name: Push trained model to DVC
      run: |
        dvc add models/cancer_detection_model.h5
        git add models/cancer_detection_model.h5.dvc
        git commit -m "Add trained model"
        dvc push
