name: MLOps Workflow

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Config aws credentials
      run: |
        dvc remote add -d myremote s3://mlopstest123456/dvc-storage
        dvc remote modify myremote access_key_id AKIA6ODU2ZDFGAK4S3EU
        dvc remote modify myremote secret_access_key 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

    - name: Repro data
      run: |
        dvc repro
        
    - name: Pull data from DVC storage
      run: |
        dvc pull

    - name: Train model
      run: |
        python3 src/train.py --data_path data/chest_xray --epochs 10 --batch_size 32

    - name: Push trained model to DVC
      run: |
        dvc add models/cancer_detection_model.h5
        git add models/cancer_detection_model.h5.dvc
        git commit -m "Add trained model"
        dvc push
