name: MLOps Workflow

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest
    environment: mlops_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Add dataset to DVC
      run: |
        mkdir -p data/chest_xray
        ls -la data/
        dvc add data/chest_xray

    - name: Config aws credentials
      run: |
        dvc remote add -d myremote ${{ secrets.AWS_S3_BUCKET_URL }} --force
        dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region eu-west-3

    - name: Download model from S3
      run: |
        aws s3 cp ${{ secrets.AWS_S3_BUCKET_URL }}/models/cancer_detection_model.h5 models/cancer_detection_model.h5

    - name: Check if model is downloaded
      run: | 
        ls -l models/cancer_detection_model.h5
        ls .dvc/cache
        mv models/* /home/runner/work/taller_mlops/taller_mlops/models/

    - name: Pull data from DVC storage
      run: |
        dvc pull -vv -f
    
    - name: Train model
      run: |
        python3 src/train.py --data_path data/chest_xray --epochs 10 --batch_size 32

    - name: Push trained model to DVC
      run: |
        dvc add models/cancer_detection_model.h5 -f
        dvc push -f
